COMP: Fix error: ‘class vtkMRMLScalarVolumeNode’ has no member named ‘SetLabelMap’
This commit finalizes the transition to the new labelMap node introduced
in Slicer 4.5 and initiated in 064c8eb (COMP: Use vtkMRMLLabelMapVolumeNode)

See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/Slicer#MRML:_Slicer_4.5:_Introduction_of_vtkMRMLLabelMapVolumeNode